project_id = "zxgmmdbffzmaxwfgdwlu"

[functions.compact-statistics]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.cleanup-tts-cache]
verify_jwt = false

[functions.cleanup-patient-calls]
verify_jwt = false

[functions.cleanup-duplicates]
verify_jwt = false

[functions.generate-hour-audio]
verify_jwt = false

[functions.update-cache]
verify_jwt = false

[functions.google-cloud-tts]
verify_jwt = false

[functions.telegram-alert]
verify_jwt = false

[functions.send-daily-statistics]
verify_jwt = false

[functions.database-stats]
verify_jwt = false

[functions.tv-reload-command]
verify_jwt = false

[functions.cache-destination-phrases]
verify_jwt = false

[functions.generate-marketing-audio]
verify_jwt = false
