project_id = "zxgmmdbffzmaxwfgdwlu"

[functions.compact-statistics]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.cleanup-tts-cache]
verify_jwt = false

[functions.cleanup-patient-calls]
verify_jwt = false

[functions.generate-hour-audio]
verify_jwt = false
